// frontend/src/pages/Register.tsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import api from '@/lib/api';
import { UserRole } from '@/types/api-types';

export default function Register() {
  const [formData, setFormData] = useState({
    email: '',
    password: '',
    confirmPassword: '',
    full_name: '',
    role: UserRole.DOCTOR,
  });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    // Validate password
    if (formData.password !== formData.confirmPassword) {
      setError('Passwords do not match');
      return;
    }

    if (formData.password.length < 8) {
      setError('Password must be at least 8 characters');
      return;
    }

    setLoading(true);

    try {
      await api.auth.register({
        email: formData.email,
        password: formData.password,
        full_name: formData.full_name,
        role: formData.role,
      });

      // Redirect to login
      navigate('/login', {
        state: { message: 'Registration successful! Please log in.' },
      });
    } catch (err: any) {
      setError(err?.error?.detail || 'Registration failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-50 px-4 py-12 sm:px-6 lg:px-8">
      <div className="w-full max-w-md space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">
            Create an account
          </h2>
          <p className="mt-2 text-center text-sm text-gray-600">
            Dictat Medical Dictation Service
          </p>
        </div>

        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          {error && (
            <div className="rounded-md bg-red-50 p-4">
              <p className="text-sm text-red-800">{error}</p>
            </div>
          )}

          <div className="space-y-4">
            <div>
              <label htmlFor="full_name" className="block text-sm font-medium text-gray-700">
                Full Name
              </label>
              <input
                id="full_name"
                name="full_name"
                type="text"
                required
                value={formData.full_name}
                onChange={(e) => setFormData({ ...formData, full_name: e.target.value })}
                className="mt-1 block w-full rounded-md border-0 px-3 py-2 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-600 sm:text-sm sm:leading-6"
                placeholder="Dr. Jane Smith"
              />
            </div>

            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-700">
                Email address
              </label>
              <input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                required
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                className="mt-1 block w-full rounded-md border-0 px-3 py-2 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-600 sm:text-sm sm:leading-6"
                placeholder="doctor@example.com"
              />
            </div>

            <div>
              <label htmlFor="role" className="block text-sm font-medium text-gray-700">
                Role
              </label>
              <select
                id="role"
                name="role"
                value={formData.role}
                onChange={(e) => setFormData({ ...formData, role: e.target.value as UserRole })}
                className="mt-1 block w-full rounded-md border-0 px-3 py-2 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-primary-600 sm:text-sm sm:leading-6"
              >
                <option value={UserRole.DOCTOR}>Doctor</option>
                <option value={UserRole.SECRETARY}>Secretary</option>
                <option value={UserRole.ADMIN}>Admin</option>
              </select>
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700">
                Password
              </label>
              <input
                id="password"
                name="password"
                type="password"
                autoComplete="new-password"
                required
                value={formData.password}
                onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                className="mt-1 block w-full rounded-md border-0 px-3 py-2 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-600 sm:text-sm sm:leading-6"
                placeholder="Minimum 8 characters"
              />
            </div>

            <div>
              <label htmlFor="confirmPassword" className="block text-sm font-medium text-gray-700">
                Confirm Password
              </label>
              <input
                id="confirmPassword"
                name="confirmPassword"
                type="password"
                autoComplete="new-password"
                required
                value={formData.confirmPassword}
                onChange={(e) => setFormData({ ...formData, confirmPassword: e.target.value })}
                className="mt-1 block w-full rounded-md border-0 px-3 py-2 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-600 sm:text-sm sm:leading-6"
              />
            </div>
          </div>

          <div>
            <button
              type="submit"
              disabled={loading}
              className="group relative flex w-full justify-center rounded-md bg-primary-600 px-3 py-2 text-sm font-semibold text-white hover:bg-primary-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-600 disabled:opacity-50"
            >
              {loading ? 'Creating account...' : 'Create account'}
            </button>
          </div>

          <div className="text-center text-sm">
            <Link to="/login" className="font-medium text-primary-600 hover:text-primary-500">
              Already have an account? Sign in
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
}

// frontend/src/routes/auth/register/+page.svelte
<script lang="ts">
  import { authStore } from '$stores/auth';
  import { UserRole } from '$lib/api';
  import LoadingSpinner from '$components/shared/LoadingSpinner.svelte';

  let email = '';
  let password = '';
  let confirmPassword = '';
  let fullName = '';
  let role: UserRole = UserRole.DOCTOR;
  let loading = false;
  let validationError = '';

  const validateForm = (): boolean => {
    if (password.length < 8) {
      validationError = 'Password must be at least 8 characters';
      return false;
    }

    if (!/[A-Z]/.test(password)) {
      validationError = 'Password must contain at least one uppercase letter';
      return false;
    }

    if (!/[a-z]/.test(password)) {
      validationError = 'Password must contain at least one lowercase letter';
      return false;
    }

    if (!/[0-9]/.test(password)) {
      validationError = 'Password must contain at least one digit';
      return false;
    }

    if (password !== confirmPassword) {
      validationError = 'Passwords do not match';
      return false;
    }

    validationError = '';
    return true;
  };

  const handleSubmit = async (e: Event) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    loading = true;

    try {
      await authStore.register({
        email,
        password,
        full_name: fullName,
        role
      });
    } catch (error) {
      // Error is handled in the store
    } finally {
      loading = false;
    }
  };
</script>

<svelte:head>
  <title>Register - Dictat</title>
</svelte:head>

<div class="flex min-h-screen items-center justify-center bg-gray-50 px-4 py-12 sm:px-6 lg:px-8">
  <div class="w-full max-w-md space-y-8">
    <div>
      <h2 class="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">
        Create your account
      </h2>
      <p class="mt-2 text-center text-sm text-gray-600">Join the Dictat platform</p>
    </div>

    <form class="mt-8 space-y-6" on:submit={handleSubmit}>
      {#if $authStore.error || validationError}
        <div class="rounded-md bg-red-50 p-4">
          <p class="text-sm text-red-800">{validationError || $authStore.error}</p>
        </div>
      {/if}

      <div class="space-y-4">
        <div>
          <label for="fullName" class="label">Full Name</label>
          <input
            id="fullName"
            name="fullName"
            type="text"
            required
            bind:value={fullName}
            class="input"
            placeholder="Dr. Jane Smith"
          />
        </div>

        <div>
          <label for="email" class="label">Email address</label>
          <input
            id="email"
            name="email"
            type="email"
            autocomplete="email"
            required
            bind:value={email}
            class="input"
            placeholder="doctor@example.com"
          />
        </div>

        <div>
          <label for="role" class="label">Role</label>
          <select id="role" name="role" bind:value={role} class="input">
            <option value={UserRole.DOCTOR}>Doctor</option>
            <option value={UserRole.SECRETARY}>Secretary</option>
            <option value={UserRole.ADMIN}>Admin</option>
          </select>
        </div>

        <div>
          <label for="password" class="label">Password</label>
          <input
            id="password"
            name="password"
            type="password"
            autocomplete="new-password"
            required
            bind:value={password}
            class="input"
            placeholder="••••••••"
          />
          <p class="mt-1 text-xs text-gray-500">
            Min 8 characters with uppercase, lowercase, and digit
          </p>
        </div>

        <div>
          <label for="confirmPassword" class="label">Confirm Password</label>
          <input
            id="confirmPassword"
            name="confirmPassword"
            type="password"
            autocomplete="new-password"
            required
            bind:value={confirmPassword}
            class="input"
            placeholder="••••••••"
          />
        </div>
      </div>

      <div>
        <button type="submit" disabled={loading} class="btn-primary w-full">
          {#if loading}
            <div class="flex items-center justify-center gap-2">
              <LoadingSpinner size="sm" />
              <span>Creating account...</span>
            </div>
          {:else}
            Register
          {/if}
        </button>
      </div>

      <div class="text-center text-sm">
        <span class="text-gray-600">Already have an account?</span>
        <a href="/auth/login" class="font-medium text-primary-600 hover:text-primary-500">
          Sign in here
        </a>
      </div>
    </form>
  </div>
</div>
